#!/usr/bin/env python3
"""Pack the assets/ tree into a single DEFLATE-compressed archive and emit it
both as a binary .pak and as an embeddable C header (byte array).

The compression is *raw* DEFLATE (zlib wbits=-15, no zlib header/checksum) so
that raylib's DecompressData() (sdefl/sinfl) can inflate each blob directly.

Pack format (all integers little-endian uint32):
    magic   : 4 bytes  "SWPK"
    version : uint32    = 1
    count   : uint32    number of entries
    index   : count * { pathLen:uint32, path:bytes[pathLen],
                        offset:uint32, rawSize:uint32, compSize:uint32 }
    blobs   : concatenated raw-DEFLATE streams (offset is relative to blob start)
"""

import argparse
import struct
import sys
import zlib
from pathlib import Path

MAGIC = b"SWPK"
VERSION = 1

# Source-only / editor files that must never ship inside the game binary.
SKIP_SUFFIXES = {".aseprite", ".ase"}
SKIP_NAMES = {".gitignore", ".gitkeep", "Thumbs.db", ".DS_Store"}


def collect_files(assets_dir: Path):
    files = []
    for path in sorted(assets_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() in SKIP_SUFFIXES or path.name in SKIP_NAMES:
            continue
        files.append(path)
    return files


def deflate_raw(data: bytes) -> bytes:
    comp = zlib.compressobj(9, zlib.DEFLATED, -15)
    return comp.compress(data) + comp.flush()


def build_pack(assets_dir: Path, files):
    index = []          # (rel_path_bytes, offset, raw_size, comp_size)
    blobs = bytearray()
    for path in files:
        raw = path.read_bytes()
        comp = deflate_raw(raw)
        # Store the path relative to the assets/ parent, using forward slashes,
        # so keys match the "assets/..." strings used in the game code.
        rel = path.relative_to(assets_dir.parent).as_posix()
        index.append((rel.encode("utf-8"), len(blobs), len(raw), len(comp)))
        blobs.extend(comp)

    out = bytearray()
    out += MAGIC
    out += struct.pack("<II", VERSION, len(index))
    for rel, offset, raw_size, comp_size in index:
        out += struct.pack("<I", len(rel))
        out += rel
        out += struct.pack("<III", offset, raw_size, comp_size)
    out += blobs
    return bytes(out), index


def write_header(header_path: Path, pack: bytes):
    header_path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Generated by tools/pack_assets.py -- do not edit.")
    lines.append("#ifndef APP_ASSETS_ASSETS_PAK_H")
    lines.append("#define APP_ASSETS_ASSETS_PAK_H")
    lines.append("")
    lines.append(f"static const unsigned int g_assetsPakSize = {len(pack)}u;")
    lines.append("static const unsigned char g_assetsPak[] = {")
    row = []
    for i, b in enumerate(pack):
        row.append(f"{b}")
        if len(row) == 20:
            lines.append("    " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ",".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    header_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--assets", required=True, type=Path, help="path to assets/ dir")
    ap.add_argument("--out-header", required=True, type=Path, help="output C header path")
    ap.add_argument("--out-pak", type=Path, help="optional binary .pak output path")
    args = ap.parse_args()

    assets_dir = args.assets.resolve()
    if not assets_dir.is_dir():
        print(f"error: assets dir not found: {assets_dir}", file=sys.stderr)
        return 1

    files = collect_files(assets_dir)
    if not files:
        print(f"error: no packable files under {assets_dir}", file=sys.stderr)
        return 1

    pack, index = build_pack(assets_dir, files)
    write_header(args.out_header, pack)
    if args.out_pak:
        args.out_pak.parent.mkdir(parents=True, exist_ok=True)
        args.out_pak.write_bytes(pack)

    raw_total = sum(e[2] for e in index)
    print(f"packed {len(index)} files: {raw_total} -> {len(pack)} bytes "
          f"({100.0 * len(pack) / raw_total:.1f}%) into {args.out_header.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
